import { VerbsObjType } from "../Types/types";

export const verbs: VerbsObjType[] = [
  {
    word: "anticipate",
    example: "We didn’t anticipate winning this match.",
    translation: "ожидать, предвидеть",
    type: "gerund",
  },
  {
    word: "avoid",
    example: "Let’s avoid being late.",
    translation: "избегать",
    type: "gerund",
  },
  {
    word: "can’t help",
    example: "I can’t help counting those calories.",
    translation: "не могу удержаться, не могу не",
    type: "gerund",
  },
  {
    word: "complete",
    example: "He completed baking the apple pie.",
    translation: "завершать, заканчивать",
    type: "gerund",
  },
  {
    word: "consider",
    example: "She never considered moving to England.",
    translation: "рассматривать, обдумывать",
    type: "gerund",
  },
  {
    word: "delay",
    example: "We delayed moving to the new house until spring.",
    translation: "откладывать",
    type: "gerund",
  },
  {
    word: "deny",
    example: "He will deny stealing that car.",
    translation: "отрицать",
    type: "gerund",
  },
  {
    word: "despise",
    example: "She despises asking for favours.",
    translation: "презирать, ненавидеть",
    type: "gerund",
  },
  {
    word: "discuss",
    example: "We discussed buying a bigger apartment.",
    translation: "обсуждать",
    type: "gerund",
  },
  {
    word: "dislike",
    example: "She dislikes cooking and baking.",
    translation: "не любить, не нравиться",
    type: "gerund",
  },
  {
    word: "enjoy",
    example: "She enjoys reading.",
    translation: "наслаждаться",
    type: "gerund",
  },
  {
    word: "fancy",
    example: "I fancy having chicken for dinner.",
    translation: "хотеть, нравиться, желать (брит.)",
    type: "gerund",
  },
  {
    word: "finish",
    example: "She finished eating before everyone else.",
    translation: "заканчивать",
    type: "gerund",
  },
  {
    word: "forgive",
    example: "Can you forgive me for not fixing the car?",
    translation: "прощать",
    type: "gerund",
  },
  {
    word: "imagine",
    example: "Can you imagine living on the moon?",
    translation: "представлять, воображать",
    type: "gerund",
  },
  {
    word: "involve",
    example: "The new project involves writing many reports.",
    translation: "включать в себя, подразумевать",
    type: "gerund",
  },
  {
    word: "keep",
    example: "She keeps coming late!",
    translation: "продолжать",
    type: "gerund",
  },
  {
    word: "mention",
    example: "I never mentioned meeting him.",
    translation: "упоминать",
    type: "gerund",
  },
  {
    word: "mind",
    example: "Will he mind switching rooms?",
    translation: "возражать",
    type: "gerund",
  },
  {
    word: "miss",
    example: "I miss chatting with you.",
    translation: "скучать",
    type: "gerund",
  },
  {
    word: "postpone",
    example: "Let’s postpone going out of town.",
    translation: "откладывать",
    type: "gerund",
  },
  {
    word: "practise",
    example: "He practises playing the guitar daily.",
    translation: "практиковаться, тренироваться",
    type: "gerund",
  },
  {
    word: "recommend",
    example: "The doctor recommends resting in bed.",
    translation: "рекомендовать",
    type: "gerund",
  },
  {
    word: "report",
    example: "They reported seeing her leave with a stranger.",
    translation: "сообщать",
    type: "gerund",
  },
  {
    word: "resent",
    example: "He resents doing it all by himself.",
    translation: "негодовать, возмущаться",
    type: "gerund",
  },
  {
    word: "resist",
    example: "I can’t resist liking him.",
    translation: "сопротивляться, противостоять",
    type: "gerund",
  },
  {
    word: "resume",
    example: "They resumed talking after the teacher left.",
    translation: "возобновлять",
    type: "gerund",
  },
  {
    word: "risk",
    example: "Would you risk losing everything?",
    translation: "рисковать",
    type: "gerund",
  },
  {
    word: "suggest",
    example: "I suggest not taking him too seriously.",
    translation: "предлагать, советовать",
    type: "gerund",
  },
  {
    word: "tolerate",
    example: "We can’t tolerate being screamed at.",
    translation: "терпеть, выносить",
    type: "gerund",
  },
  {
    word: "understand",
    example: "He couldn’t understand her leaving so suddenly.",
    translation: "понимать",
    type: "gerund",
  },
  {
    word: "worth",
    example: "It’s worth visiting the cathedral if you have time.",
    translation: "стоит, заслуживает",
    type: "gerund",
  },
  {
    word: "afford",
    example: "He has no money so he can’t afford to buy a car.",
    translation: "позволить себе",
    type: "infinitiveTo",
  },
  {
    word: "agree",
    example: "They agreed to give him a try.",
    translation: "соглашаться",
    type: "infinitiveTo",
  },
  {
    word: "appear",
    example: "He appeared to know everything.",
    translation: "казаться, появляться",
    type: "infinitiveTo",
  },
  {
    word: "arrange",
    example: "I have arranged to meet him on Monday.",
    translation: "договариваться, организовывать",
    type: "infinitiveTo",
  },
  {
    word: "ask",
    example: "She asked to see her doctor.",
    translation: "просить",
    type: "infinitiveTo",
  },
  {
    word: "choose",
    example: "We chose to ignore it.",
    translation: "выбирать",
    type: "infinitiveTo",
  },
  {
    word: "claim",
    example: "He claims to be an expert.",
    translation: "утверждать",
    type: "infinitiveTo",
  },
  {
    word: "decide",
    example: "She decided not to go to the party.",
    translation: "решать",
    type: "infinitiveTo",
  },
  {
    word: "demand",
    example: "I demand to see the person in charge!",
    translation: "требовать",
    type: "infinitiveTo",
  },
  {
    word: "deserve",
    example: "He deserves to win the contest.",
    translation: "заслуживать",
    type: "infinitiveTo",
  },
  {
    word: "expect",
    example: "He expected to be home sooner.",
    translation: "ожидать",
    type: "infinitiveTo",
  },
  {
    word: "fail",
    example: "They failed to follow the instructions.",
    translation: "провалиться, потерпеть неудачу",
    type: "infinitiveTo",
  },
  {
    word: "get",
    example: "It’s not fair that she gets to see him first.",
    translation: "получать, доставаться (разг.)",
    type: "infinitiveTo",
  },
  {
    word: "happen",
    example: "I happened to pass by, so we had a chat.",
    translation: "случаться",
    type: "infinitiveTo",
  },
  {
    word: "hesitate",
    example: "Don’t hesitate to call.",
    translation: "стесняться, колебаться",
    type: "infinitiveTo",
  },
  {
    word: "hope",
    example: "I hope to see you soon.",
    translation: "надеяться",
    type: "infinitiveTo",
  },
  {
    word: "intend",
    example: "She didn’t intend to hurt you.",
    translation: "намереваться",
    type: "infinitiveTo",
  },
  {
    word: "learn",
    example: "He learned to speak Spanish very quickly.",
    translation: "учить",
    type: "infinitiveTo",
  },
  {
    word: "manage",
    example: "We managed to finish everything on time.",
    translation: "удаваться",
    type: "infinitiveTo",
  },
  {
    word: "offer",
    example: "He offered to go for a walk.",
    translation: "предлагать",
    type: "infinitiveTo",
  },
  {
    word: "prepare",
    example: "We were preparing to leave when he arrived.",
    translation: "готовиться",
    type: "infinitiveTo",
  },
  {
    word: "pretend",
    example: "She pretended not to hear a word.",
    translation: "притворяться",
    type: "infinitiveTo",
  },
  {
    word: "promise",
    example: "She promised to take us with her next time.",
    translation: "обещать",
    type: "infinitiveTo",
  },
  {
    word: "refuse",
    example: "I refuse to cooperate.",
    translation: "отказываться",
    type: "infinitiveTo",
  },
  {
    word: "seem",
    example: "It seems to be broken.",
    translation: "казаться",
    type: "infinitiveTo",
  },
  {
    word: "swear",
    example: "He swore to take revenge.",
    translation: "клясться",
    type: "infinitiveTo",
  },
  {
    word: "tend",
    example: "These plants tend to grow slowly.",
    translation: "иметь тенденцию",
    type: "infinitiveTo",
  },
  {
    word: "threaten",
    example: "He has threatened to hurt us.",
    translation: "угрожать",
    type: "infinitiveTo",
  },
  {
    word: "wait",
    example: "The runners were waiting to start.",
    translation: "ждать",
    type: "infinitiveTo",
  },
  {
    word: "want",
    example: "I want to speak with you in private.",
    translation: "хотеть",
    type: "infinitiveTo",
  },
  {
    word: "wish",
    example: "I wish to change my address.",
    translation: "желать",
    type: "infinitiveTo",
  },
  {
    word: "would like",
    example: "I would like to make a comment",
    translation: "хотел бы",
    type: "infinitiveTo",
  },
  {
    word: "can",
    example: "I can help you if you have any problems.",
    translation: "мочь, уметь",
    type: "infinitiveWithoutTo",
  },
  {
    word: "could",
    example: "When I was young I could play the piano.",
    translation: "мог, умел",
    type: "infinitiveWithoutTo",
  },
  {
    word: "had better",
    example: "You had better finish your homework before it’s too late.",
    translation: "следует, лучше бы",
    type: "infinitiveWithoutTo",
  },
  {
    word: "let (+object +verb)",
    example: "My parents never let me go out late when I was young.",
    translation: "позволять",
    type: "infinitiveWithoutTo",
  },
  {
    word: "make (+object +verb)",
    example: "The boss made her employees stay late.",
    translation: "заставлять",
    type: "infinitiveWithoutTo",
  },
  {
    word: "may",
    example: "I may go to the party, but I’m not sure.",
    translation: "мочь, возможно",
    type: "infinitiveWithoutTo",
  },
  {
    word: "might",
    example: "They might make money with the new business plan.",
    translation: "мог бы, возможно",
    type: "infinitiveWithoutTo",
  },
  {
    word: "must",
    example: "You must renew your passport before travelling abroad.",
    translation: "должен",
    type: "infinitiveWithoutTo",
  },
  {
    word: "should",
    example: "You should try the new restaurant in the centre.",
    translation: "следует, должен",
    type: "infinitiveWithoutTo",
  },
  {
    word: "would rather",
    example: "I would rather cook at home than eat out.",
    translation: "предпочел бы",
    type: "infinitiveWithoutTo",
  },

  {
    word: "can’t stand",
    example:
      "She can’t stand sitting in the sun when it’s hot.\nShe can’t stand to sit in the sun when it’s hot.",
    translation: "не выносить",
    type: "both",
  },
  {
    word: "continue",
    example:
      "He continued talking when I asked him to stop.\nHe continued to talk when I asked him to stop.",
    translation: "продолжать",
    type: "both",
  },
  {
    word: "prefer",
    example: "We prefer eating dinner early.\nWe prefer to eat dinner early.",
    translation: "предпочитать",
    type: "both",
  },
  {
    word: "start",
    example:
      "She started working at the company in May.\nShe started to work at the company in May.",
    translation: "начинать",
    type: "both",
  },

  {
    word: "forget",
    example:
      "He forgot lending me the money.\n(He has no memory of lending the money.)\nHe forgot to lend me the money.\n(He forgot to complete the intended action.)",
    translation: "забывать",
    type: "bothDifferent",
  },
  {
    word: "remember",
    example:
      "I remember locking the storage.\n(I have a memory of locking the storage.)\nI must remember to lock the storage.\n(I must remember to complete the intended action.)",
    translation: "помнить",
    type: "bothDifferent",
  },
  {
    word: "need",
    example:
      "The house needs cleaning.\n(Passive voice, we don’t know who will clean.)\nWe need to clean the house.\n(Active voice, the subject does the action.)",
    translation: "нуждаться",
    type: "bothDifferent",
  },
  {
    word: "regret",
    example:
      "I regret going to your wedding.\n(I went, and now I regret it.)\nI regret to tell you I can’t go to your wedding.\n(I feel bad that I plan to tell you that I won’t go.)",
    translation: "сожалеть",
    type: "bothDifferent",
  },
  {
    word: "stop",
    example:
      "She stopped chatting.\n(She was chatting, and then she stopped.)\nShe stopped to chat.\n(She was doing something, then she stopped and chatted.)",
    translation: "останавливаться, прекращать",
    type: "bothDifferent",
  },
  {
    word: "try",
    example:
      "They tried using bleach to clean the stain.\n(They experimented with bleach as an option.)\nThey tried to use bleach to clean the stain.\n(The attempt to use bleach was a failure.)",
    translation: "пытаться",
    type: "bothDifferent",
  },
];
